### ISSUE TITLE
plágio ou inspiração?

### ISSUE THREAD

**Issue by vmnog** [micaelgomestavares/CinemaScore#1]
seu projeto parece muito com o https://plotwist.app 🤨

**Comment by micaelgomestavares** [comment]
O projeto é sim inspirado no plotwist, mas aqui é apenas um projeto de portfólio e não irá ser comercializado. E o fato de utilizarmos o shadcn/ui como biblioteca de componentes faz tudo ficar mais parecido.

**Comment by vmnog** [comment]
> O projeto é sim inspirado no plotwist, mas aqui é apenas um projeto de portfólio e não irá ser comercializado. E o fato de utilizarmos o shadcn/ui como biblioteca de componentes faz tudo ficar mais parecido.

Show de bola, ficou massa, só uma coisa que >eu< pessoalmente faria, era mencionar o projeto original como inspiração, além de ser algo de "bom tom" eticamente falando, pode até ser algo bom de você contar nas entrevistas tipo "eu vi esse projeto achei massa e quis fazer a minha versão e os desafios q eu tive foi X, Y e Z...". 

Abraço!

**Comment by micaelgomestavares** [comment]
Obrigado pelo feedback, irei fazer isso!
